"""empty message

Revision ID: 13caff4f71d2
Revises: 1f971aa891f2
Create Date: 2024-05-05 16:44:12.880351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13caff4f71d2'
down_revision = '1f971aa891f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
