"""empty message

Revision ID: 334cc4a7ff0a
Revises: b632408a6de8
Create Date: 2024-03-26 17:37:01.206496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334cc4a7ff0a'
down_revision = 'b632408a6de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forward_to_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.drop_column('forward_to_admin')

    # ### end Alembic commands ###
