"""empty message

Revision ID: 4e89b532fdd4
Revises: 
Create Date: 2024-04-09 13:30:55.900661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e89b532fdd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_data',
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('crc_no', sa.Integer(), nullable=True),
    sa.Column('father_name', sa.String(length=30), nullable=True),
    sa.Column('father_cnic', sa.String(length=50), nullable=True),
    sa.Column('father_finger', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=30), nullable=True),
    sa.Column('mother_cnic', sa.String(length=50), nullable=True),
    sa.Column('mother_finger', sa.String(length=255), nullable=True),
    sa.Column('send_comment', sa.String(length=255), nullable=True),
    sa.Column('received_comment', sa.String(length=255), nullable=True),
    sa.Column('employee_province_sno', sa.Integer(), nullable=True),
    sa.Column('employee_district_sno', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('forward_to_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_district_sno'], ['district.district_sno'], ),
    sa.ForeignKeyConstraint(['employee_province_sno'], ['province.province_sno'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('par_id'),
    sa.UniqueConstraint('father_cnic'),
    sa.UniqueConstraint('mother_cnic')
    )
    op.create_table('child_data',
    sa.Column('chi_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=30), nullable=True),
    sa.Column('child_birth_date', sa.Date(), nullable=False),
    sa.Column('child_gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['par_id'], ['parent_data.par_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('chi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_data')
    op.drop_table('parent_data')
    # ### end Alembic commands ###
