"""empty message

Revision ID: 65c6f672bf1e
Revises: e05a6272d019
Create Date: 2024-03-26 05:40:57.423740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c6f672bf1e'
down_revision = 'e05a6272d019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_data',
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=30), nullable=True),
    sa.Column('father_contact', sa.String(length=50), nullable=True),
    sa.Column('mother_name', sa.String(length=30), nullable=True),
    sa.Column('mother_contact', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('par_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_data')
    # ### end Alembic commands ###
