"""empty message

Revision ID: 679029cbecf5
Revises: 4e89b532fdd4
Create Date: 2024-04-09 15:06:45.095920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679029cbecf5'
down_revision = '4e89b532fdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_cnic', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['new_cnic'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('new_cnic')

    # ### end Alembic commands ###
