"""empty message

Revision ID: 6ee548a40a57
Revises: 679029cbecf5
Create Date: 2024-04-09 15:10:12.713924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee548a40a57'
down_revision = '679029cbecf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disability', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_data', schema=None) as batch_op:
        batch_op.drop_column('disability')

    # ### end Alembic commands ###
