"""empty message

Revision ID: 7ab4917ddc60
Revises: 8b19c31667b8
Create Date: 2024-04-09 22:22:37.683461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab4917ddc60'
down_revision = '8b19c31667b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_boy_handover',
    sa.Column('ho_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('drop_address', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['par_id'], ['parent_data.par_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ho_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_boy_handover')
    # ### end Alembic commands ###
