"""empty message

Revision ID: 8b19c31667b8
Revises: cc61c3e1e58e
Create Date: 2024-04-09 21:24:17.595270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b19c31667b8'
down_revision = 'cc61c3e1e58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
