"""empty message

Revision ID: a1d84fd04cbc
Revises: 8a0736e7f326
Create Date: 2024-05-05 11:59:34.410231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d84fd04cbc'
down_revision = '8a0736e7f326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('n_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_info', sa.String(length=50), nullable=True),
    sa.Column('is_check_by_manager', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_employee', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_parent', sa.Boolean(), nullable=True),
    sa.Column('is_check_by_delivery_boy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('n_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
