"""empty message

Revision ID: b8afbec543a0
Revises: 054e9c8252ad
Create Date: 2024-03-26 06:22:34.647037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8afbec543a0'
down_revision = '054e9c8252ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_cnic', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_cnic', sa.String(length=50), nullable=True))
        batch_op.drop_column('mother_contact')
        batch_op.drop_column('father_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_contact', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_contact', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('mother_cnic')
        batch_op.drop_column('father_cnic')

    # ### end Alembic commands ###
