"""empty message

Revision ID: c23ddad16e9b
Revises: f75c90754ab0
Create Date: 2024-04-06 15:38:30.679735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23ddad16e9b'
down_revision = 'f75c90754ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_finger', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mother_finger', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.drop_column('mother_finger')
        batch_op.drop_column('father_finger')

    # ### end Alembic commands ###
