"""empty message

Revision ID: cc61c3e1e58e
Revises: ed02e71d4b25
Create Date: 2024-04-09 20:36:47.404810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc61c3e1e58e'
down_revision = 'ed02e71d4b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.drop_constraint('parent_data_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('parent_data_ibfk_1', type_='foreignkey')
        batch_op.drop_column('employee_province_sno')
        batch_op.drop_column('employee_district_sno')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_province_sno', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_district_sno', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'district', ['employee_district_sno'], ['district_sno'])
        batch_op.create_foreign_key(None, 'province', ['employee_province_sno'], ['province_sno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_district_sno')
        batch_op.drop_column('employee_province_sno')

    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_district_sno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employee_province_sno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('parent_data_ibfk_1', 'district', ['employee_district_sno'], ['district_sno'])
        batch_op.create_foreign_key('parent_data_ibfk_2', 'province', ['employee_province_sno'], ['province_sno'])

    # ### end Alembic commands ###
