"""empty message

Revision ID: e366551622be
Revises: 65c6f672bf1e
Create Date: 2024-03-26 05:50:59.502325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e366551622be'
down_revision = '65c6f672bf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_data',
    sa.Column('chi_id', sa.Integer(), nullable=False),
    sa.Column('par_id', sa.Integer(), nullable=False),
    sa.Column('child_name', sa.String(length=30), nullable=True),
    sa.Column('child_birth_date', sa.Date(), nullable=False),
    sa.Column('child_gender', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['par_id'], ['parent_data.par_id'], ),
    sa.PrimaryKeyConstraint('chi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_data')
    # ### end Alembic commands ###
