"""empty message

Revision ID: f75c90754ab0
Revises: 334cc4a7ff0a
Create Date: 2024-03-27 13:12:16.039783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75c90754ab0'
down_revision = '334cc4a7ff0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_comment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('received_comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_data', schema=None) as batch_op:
        batch_op.drop_column('received_comment')
        batch_op.drop_column('send_comment')

    # ### end Alembic commands ###
